apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  # insert your DO access token here
  access-token: "ZG9wX3YxX2JkZDE4NGY5OTY4YjUxODcwNGJiNWYxNWU4OTg1NjdlNDUyZjgxZTdkMWVjZjQwZWRhMjkwN2NiYjcyODgzNTc="
